# Generated by Django 5.0.6 on 2024-05-10 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=500)),
                ('total', models.FloatField()),
                ('paid', models.BooleanField(blank=True, default=False)),
                ('num_members', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('accepted', models.BooleanField(blank=True, default=False)),
                ('owner', models.BooleanField(blank=True, default=False)),
                ('groupid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evenly_split_api.groupsession')),
            ],
        ),
    ]
