# Generated by Django 5.0.6 on 2024-05-16 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenly_split_api', '0002_rename_username_user_user_name_remove_user_groupid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groupid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evenly_split_api.groupsession'),
        ),
    ]
