# Generated by Django 5.0.6 on 2024-05-16 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenly_split_api', '0003_user_groupid'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsession',
            name='owner',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='groupid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evenly_split_api.groupsession'),
        ),
    ]
