# Generated by Django 5.0.6 on 2024-05-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenly_split_api', '0004_groupsession_owner_alter_user_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsession',
            name='owner',
            field=models.CharField(max_length=500),
        ),
    ]
